source 'http://rubygems.org'

gem 'rails', '~> 3.0.9'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'

gem 'faker'

gem 'toast', "~> 0.4.0"

group 'test' do
  gem 'shoulda'
end

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
gem 'ruby-debug', :platform => :ruby_18
gem 'ruby-debug19', :require => 'ruby-debug', :platform => :ruby_19


