#
# This Gemfile configures all major Ruby on Rails Versions and switches using
# the environment variable "TOAST_TEST_RAILS_VERSION"
#
# It is called by the script ./script/test-all-rails.rb
#

source 'http://rubygems.org'

rails_version = ENV["TOAST_TEST_RAILS_VERSION"] ? ENV["TOAST_TEST_RAILS_VERSION"] : '~> 3.2'

gem 'rails', "#{rails_version}"
gem 'sqlite3', '~> 1.3.5'
gem 'i18n', '~> 0.6.0'

group :test do
  gem 'shoulda', '~> 3.4.0'
end

gemspec :path => "../.."
